// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSIPlbFpFh4RGj0W1_TCh9Ko5aNUoUm9U',
    appId: '1:374121011897:web:ce29ee1a308c7428815968',
    messagingSenderId: '374121011897',
    projectId: 'deltasoftbet',
    authDomain: 'deltasoftbet.firebaseapp.com',
    storageBucket: 'deltasoftbet.appspot.com',
    measurementId: 'G-F44YG3J25Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWwF-_uCA2Q8QtRVk-If2PcBgMG24I5VM',
    appId: '1:374121011897:android:d923315d8d66dd55815968',
    messagingSenderId: '374121011897',
    projectId: 'deltasoftbet',
    storageBucket: 'deltasoftbet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUjXm4O6_QL_pjJKu4OR3nnQeCZVcPWCk',
    appId: '1:374121011897:ios:deb8fac719dca87f815968',
    messagingSenderId: '374121011897',
    projectId: 'deltasoftbet',
    storageBucket: 'deltasoftbet.appspot.com',
    iosClientId: '374121011897-lf98tgm7cbtatbansuuo0brhlb17pr54.apps.googleusercontent.com',
    iosBundleId: 'com.example.gobet',
  );
}
